apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api-demo-sonar-success-deployment
spec:
  selector:
    matchLabels:
      app: java-api-demo-sonar-success
  template: 
    metadata:       
      labels:
        app: java-api-demo-sonar-success
    spec:            
      containers:
      - name: java-api-demo-sonar-success-container
        image: 192.168.10.30:5000/java-api-demo-sonar-success:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        imagePullSecrets:
        - name: registrypull
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080