apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: java-ingress
    namespace: java
    annotations:
        # haproorwarded-for: 'true'
        # haproxy.org/loadxy.org/check: 'true'
        # haproxy.org/f-balance: leastconn
        ingress.class: haproxy
        haproxy.org/path-rewrite: "/"
        # kubernetes.io/ingress.class: haproxy
spec:
    rules:
    - http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: java-api-demo-sonar-success-service
              port:
                number: 8080
status:
  loadBalancer:
    ingress:
      - ip: 172.16.16.100
