apiVersion: v1
kind: Service
metadata:
  name: java-api-demo-sonar-success
  labels:
    name: java-api-demo-sonar-success
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: java-api-demo-sonar-success
  type: LoadBalancer